name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info? (Use your Swipin email account)
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - Pre-release version
        - Release version
      default: 0
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
     label: Where did you download the app?
     options:
       - GitHub (Official Source)
       - F-Droid (Alternate Source)
     default: 0
     validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Important
      description: By submitting this issue, you agree to allow us to use your email to contact you or check your Swipin account. 
      options:
        - label: I agree
          required: true

  - type: checkboxes
    id: accountagree
    attributes:
      label: Important
      description: By submitting this issue, you understand that access to your Swipin account will be disabled for a few days.
      options:
        - label: I agree
          required: true
          
